### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by Utumno** [loot/skyrim#126]
Trying to generate the taglists

```
C:\Dropbox\eclipse_workspaces\python\wrye-bash\scripts>C:\_\Python27\python.exe mktaglist.py
Found Oblivion.
Found Skyrim.
Loaded the LOOT API from "../Mopy/bash/compiled", version 0.9.2.
Getting masterlist from C:\Users\MrD\AppData\Local\LOOT\Oblivion\masterlist.yaml
Oblivion masterlist converted.
Getting masterlist from C:\Users\MrD\AppData\Local\LOOT\Skyrim\masterlist.yaml
Traceback (most recent call last):
  File "mktaglist.py", line 83, in <module>
    lootDb.PlainLoad(info[1])
  File "../Mopy/bash\loot.py", line 350, in PlainLoad
    _CLoad(self._DB, _enc(masterlist), _enc(userlist) if userlist else None)
  File "../Mopy/bash\loot.py", line 238, in LootErrorCheck
    raise LootError(result)
loot.LootError: LootError: LOOT_ERROR_PARSE_FAIL:yaml-cpp: error at line 7950, column 5: bad conversion: invalid regex in 'name' key: regex_error(error_badrepeat): One of *?+{ was not preceded by a valid regular expression.
```

Latest v0.8 branch

**Comment by Utumno** [comment]
Turns out the encoding of the file got mangled somehow - redownloaded and works fine - closing
