### ISSUE TITLE
Errors when sorting plugins

### ISSUE THREAD

**Issue by EpicVikingNinja** [loot/skyrim#242]
Hi there, i went to organize my loading order and received this;
[18:20:34.501142] [warning]: Blocking load of resource at https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic

[18:20:42.931437] [error]: Exception while executing query: Git operation failed. Details: -1; corrupted loose reference file: refs/remotes/origin/v0.14-staging: libgit2 error

[18:20:42.932892] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5039: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5039:5821)

[18:20:46.699005] [error]: Exception while executing query: Git operation failed. Details: -1; corrupted loose reference file: refs/remotes/origin/v0.14-staging: libgit2 error

[18:20:46.699865] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5039: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5039:5821)

[18:28:36.692319] [error]: Exception while executing query: Git operation failed. Details: -1; corrupted loose reference file: refs/remotes/origin/v0.14-staging: libgit2 error

[18:28:36.693137] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5039: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5039:5821)

[18:34:39.159944] [error]: Exception while executing query: Git operation failed. Details: -1; corrupted loose reference file: refs/remotes/origin/v0.14-staging: libgit2 error

[18:34:39.162005] [error]: Chromium console message from http://loot/ui/app.bundle.js at line 5039: Error: Oh no, something went wrong! You can check your LOOTDebugLog.txt (you can get to it through the main menu) for more information.
    at onFailure (http://loot/ui/app.bundle.js:5039:5821)
thank you

**Comment by Ortham** [comment]
Looks like your local repository was corrupted somehow. Delete the `%LOCALAPPDATA%\LOOT\<game>\.git` folder for whatever game you'r getting that error for (the `.git` folder might be hidden), then run the masterlist update to recreate the repository.

**Comment by EpicVikingNinja** [comment]
it worked, thank you very much
